name: Build and Publish

on:
  push:
    branches: ["main"]
    paths: [".github/workflows/buildpublish.yml"]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/myapp

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image to tar.gz
        run: docker build -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest .

      - name: Save Docker image to tar.gz
        run: docker save ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest -o myapp.tar | gzip > myapp.tar.gz

      # publish artifact
      - name: Publish artifact
        uses: actions/upload-artifact@v4
        with:
          name: myapp
          path: myapp.tar.gz

  publish:
    runs-on: ubuntu-latest
    needs: build

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: myapp

      - name: Import Docker image from tar.gz
        run: docker import myapp.tar.gz ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

      # List docker images
      - name: List Docker images
        run: docker images --digests

      # Publish Docker image
      - name: Log in to the Container registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image
        run: docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

      - name: Get digest of the image
        id: getdigest
        run: |
            docker inspect ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            echo ""
            digest=$(docker inspect --format="{{.Id}}" ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest)
            echo "$digest"
            echo "digest=$(digest)" >> $GITHUB_OUTPUT

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
          subject-digest: ${{ steps.getdigest.outputs.digest }}
          push-to-registry: true
